MUL_PQ_P
eggunof/LongNumbers pull request #30
Opened 2024-11-08 10:46 UTC by hellbruh

2024-11-09 17:41 UTC, eggunof commented on libraries/numbers/src/polynomial.cc
> +  std::map<Natural, Rational, Comparator> temp = this->coefficients_;
зачем копировать?

2024-11-09 17:43 UTC, eggunof requested changes

2024-11-09 17:43 UTC, eggunof commented on libraries/numbers/src/polynomial.cc
> +    temp[it->first] = (temp[it->first]) *= (scalar);
можно просто пройтись по коеффициентам с помощью цикла (for (auto & coefficient : coefficients_)) и умножить каждый через *=

2024-11-09 17:47 UTC, eggunof commented
нет реализации `Polynomial Polynomial::operator*(const Rational &scalar) const { return {}; }`

2024-11-10 19:35 UTC, hellbruh commented on libraries/numbers/src/polynomial.cc
> +    temp[it->first] = (temp[it->first]) *= (scalar);
Пока работает лучше не трогать.

2024-11-14 18:10 UTC, eggunof approved these changes

2024-11-14 18:11 UTC, merged