GCD_NN_N
eggunof/LongNumbers pull request #55
Opened 2024-11-10 18:54 UTC by hellbruh

2024-11-10 23:13 UTC, eggunof requested changes

2024-11-10 23:13 UTC, eggunof commented on libraries/numbers/src/natural.cc
> +}
???

2024-11-11 08:37 UTC, hellbruh commented on libraries/numbers/src/natural.cc
> +}
Я хз что это, я запуталась в ветках и устала от постоянной иррациональной реструктуризации. Последний раз коммичу, надеюсь, не потеряется и никто не удалит ветку, как это случилось ранее.

2024-11-11 20:54 UTC, eggunof approved these changes

2024-11-11 20:54 UTC, merged